# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

env: 
  - TOX_ENV=py35-django-18
  - TOX_ENV=py34-django-18
  - TOX_ENV=py33-django-18
  - TOX_ENV=py27-django-18
  - TOX_ENV=py35-django-19
  - TOX_ENV=py34-django-19
  - TOX_ENV=py27-django-19
  - TOX_ENV=py35-django-110
  - TOX_ENV=py34-django-110
  - TOX_ENV=py27-django-110
  - TOX_ENV=lint
  - TOX_ENV=docs

matrix:
  fast_finish: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV

notifications:
  slack:
    rooms:
      - f4s:u17h2Cc7RhhHNtypnAu7jbgY#dev
    on_success: change
    on_failure: always
  email: false

deploy:
  provider: pypi
  user: Bruno.Alla
  password:
    secure: LZvIAhq8BCq9rWDD6NLbTQIXlUt3OReQ1x2DX2RePXi5X7DRGbwTgRYkZ4ZTJlWhqiw3/VwMSQlLnZ4UMn1FmjBgUWOVpkcnIvavt3xSAoLJf9+8x5wkx9K/twCU/4o3xFYMXm6vk3cNSDoJl52nm2/6vY2e5NQqyz1t65EfsAX1FxG62+H+ldUglyIVS+sqIybKwVT5mrJYp9Sz1n8vX9pm2PgLyeUqg63lsj5xHqsqXI3tb1hPloHBlIP6gLnq1QlHEU/4Rqvv98zUbH6dHjCEDoxdiQxrsbmvAblzj18F4nSZ+kz9K4uLYRIMJ9lRNtnd1BpQxw1XctV191klKaHpcl+g0UP36oo+psb3c9Kh2MZ0G0uJTHRzlKEqG596f3TeHD3KkB/4PVD4vXMjMNYpHtB9nevUo7pgI2daA/aAnGcvr3WVo2K4ppm8/B1v2nx3zWbcxDuYwTL1hePSt9gljqMmKFD7R+uDvIQmBECJxxq8VLxVfWYjAyToFbqinEJqNXeX9SyAogzo+a8gVb29t68jPE5RrD0AVWTXgvBQhs/2qNsidVpS0gur9001D7Acx8ra27YfrkmAZsr5RaAzBENtbrChcsoneDLjKsMFY/81l5RyJhLmkcfDFCkinpWwBaFZjlEcft13N91wO4b+6yFHYhZrUzkJMh11cXU=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: founders4schools/django-surveys
    branch: master
    condition: $TOX_ENV = py35-django-110
