# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: false

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=master

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV="docs"
  exclude:
    - python: "3.7-dev"
      env: DJANGO=1.11

  allow_failures:
    - env: DJANGO=2.0
    - env: DJANGO=2.1
    - env: DJANGO=master
    - python: "3.7-dev"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements_test.txt

# command to run tests using coverage, e.g. python setup.py test
script: tox

after_success:
  - codecov -e TOXENV,DJANGO

notifications:
  slack:
    rooms:
      - f4s:u17h2Cc7RhhHNtypnAu7jbgY#dev
    on_success: change
    on_failure: always
  email: false

deploy:
  provider: pypi
  user: Bruno.Alla
  password:
    secure: NY3eIiWFqPrmZBgzgA3nTe77UadBnlaK6jR2CQyD9DKtxjOsivI1N97+2mmx9BKpb5VhBDCqgYWgXIk+ZphDcVuX2ZL+7v2D+LBbtNgh0FlYwORcI3bzBTCuk4YvHBANLlG6sueALiBHXcCVoecO5sNE19JDQ6V7KIvjt9xQt43ausdkpgFOE5Q7lAsrszLzNgRBwfJE5b56QRREjFSrX42KH24Afek6yyMOfvKBgXzhVt22ZRNlwqWbjOCDUDQYVCu/ST94liTgQ2s9PTV85+mhJbnbV//k+wCfnmk3CYwsArQLtLJfc/9zx4lW8aieaejn88I24bv1UXh0f7Am5WbY3irc9NXMev7N6kCzC9RuwEtC349RVVxPF47ZdWSduLCSU+00vpBf6G8Qb+aFtgZIcmLzxg5V1ASPGeKi3NJbY3BcozEuyqbedH5cCiKrxnPSKhxiJRBCmK645Ds7tI4DZhvs9tYDxGW3KrG1JxlEWxhkLpB+QhOIBgiIaUx95tpOMRJYdpYyCcvoClWljDz8uPssnAAB1EBbqH4yNXo1UjaHENe3pvoEOkNnRORqXJ9f0no17wlfDPRvnDLMTcQUTe22fLQ5xPMGuyidUVgidFPUgOhp+NRcxQj1+l2FsqYL5DtikNvQBhuTEz74wR/3bKV2uzIcQo2gnt7WGeU=
  on:
    branch: master
    repo: founders4schools/django-surveys
    tags: true
    python: 3.6
    env: TOXENV=py36-django111
